-- MySQL Script generated by MySQL Workbench
-- Sun Sep 29 13:05:16 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Cars`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Cars` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Cars` (
  `idCars` INT NOT NULL AUTO_INCREMENT,
  `Brand` VARCHAR(45) NOT NULL,
  `Model` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCars`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Contact info`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Contact info` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Contact info` (
  `idContact info` INT NOT NULL AUTO_INCREMENT,
  `City` VARCHAR(45) NOT NULL,
  `Street` VARCHAR(45) NOT NULL,
  `Phone` INT NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idContact info`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Dormitories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Dormitories` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Dormitories` (
  `idDormitories` INT NOT NULL AUTO_INCREMENT,
  `Contact info_idContact info` INT NOT NULL,
  PRIMARY KEY (`idDormitories`, `Contact info_idContact info`),
  INDEX `fk_Dormitories_Contact info1_idx` (`Contact info_idContact info` ASC) VISIBLE,
  CONSTRAINT `fk_Dormitories_Contact info1`
    FOREIGN KEY (`Contact info_idContact info`)
    REFERENCES `mydb`.`Contact info` (`idContact info`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Attendance`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Attendance` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Attendance` (
  `idAttendance` INT NOT NULL AUTO_INCREMENT,
  `date` DATE NOT NULL,
  `status` TINYINT NULL,
  `remark` VARCHAR(45) NULL,
  PRIMARY KEY (`idAttendance`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Students`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Students` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Students` (
  `idStudent` INT NOT NULL AUTO_INCREMENT,
  `FirstName` VARCHAR(45) NOT NULL,
  `LastName` VARCHAR(45) NOT NULL,
  `Cars_idCars` INT NOT NULL,
  `Contact info_idContact info` INT NOT NULL,
  `Dormitories_idDormitories` INT NOT NULL,
  `Dormitories_Contact info_idContact info` INT NOT NULL,
  `Attendance_idAttendance` INT NOT NULL,
  PRIMARY KEY (`idStudent`, `Contact info_idContact info`, `Attendance_idAttendance`),
  INDEX `fk_Students_Cars_idx` (`Cars_idCars` ASC) VISIBLE,
  INDEX `fk_Students_Contact info1_idx` (`Contact info_idContact info` ASC) VISIBLE,
  INDEX `fk_Students_Dormitories1_idx` (`Dormitories_idDormitories` ASC, `Dormitories_Contact info_idContact info` ASC) VISIBLE,
  INDEX `fk_Students_Attendance1_idx` (`Attendance_idAttendance` ASC) VISIBLE,
  CONSTRAINT `fk_Students_Cars`
    FOREIGN KEY (`Cars_idCars`)
    REFERENCES `mydb`.`Cars` (`idCars`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Students_Contact info1`
    FOREIGN KEY (`Contact info_idContact info`)
    REFERENCES `mydb`.`Contact info` (`idContact info`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Students_Dormitories1`
    FOREIGN KEY (`Dormitories_idDormitories` , `Dormitories_Contact info_idContact info`)
    REFERENCES `mydb`.`Dormitories` (`idDormitories` , `Contact info_idContact info`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Students_Attendance1`
    FOREIGN KEY (`Attendance_idAttendance`)
    REFERENCES `mydb`.`Attendance` (`idAttendance`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Courses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Courses` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Courses` (
  `idCourses` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NULL,
  PRIMARY KEY (`idCourses`),
  UNIQUE INDEX `idCourses_UNIQUE` (`idCourses` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Courses_has_Students`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Courses_has_Students` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Courses_has_Students` (
  `Courses_idCourses` INT NOT NULL,
  `Students_idStudent` INT NOT NULL,
  PRIMARY KEY (`Courses_idCourses`, `Students_idStudent`),
  INDEX `fk_Courses_has_Students_Students1_idx` (`Students_idStudent` ASC) VISIBLE,
  INDEX `fk_Courses_has_Students_Courses1_idx` (`Courses_idCourses` ASC) VISIBLE,
  CONSTRAINT `fk_Courses_has_Students_Courses1`
    FOREIGN KEY (`Courses_idCourses`)
    REFERENCES `mydb`.`Courses` (`idCourses`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Courses_has_Students_Students1`
    FOREIGN KEY (`Students_idStudent`)
    REFERENCES `mydb`.`Students` (`idStudent`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Teachers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Teachers` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Teachers` (
  `idTeachers` INT NOT NULL AUTO_INCREMENT,
  `FirstName` VARCHAR(45) NOT NULL,
  `LastName` VARCHAR(45) NOT NULL,
  `Salary` INT NOT NULL,
  `Contact info_idContact info` INT NOT NULL,
  `Cars_idCars` INT NOT NULL,
  PRIMARY KEY (`idTeachers`, `Contact info_idContact info`),
  INDEX `fk_Teachers_Contact info1_idx` (`Contact info_idContact info` ASC) VISIBLE,
  INDEX `fk_Teachers_Cars1_idx` (`Cars_idCars` ASC) VISIBLE,
  CONSTRAINT `fk_Teachers_Contact info1`
    FOREIGN KEY (`Contact info_idContact info`)
    REFERENCES `mydb`.`Contact info` (`idContact info`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Teachers_Cars1`
    FOREIGN KEY (`Cars_idCars`)
    REFERENCES `mydb`.`Cars` (`idCars`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Courses_has_Teachers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Courses_has_Teachers` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Courses_has_Teachers` (
  `Courses_idCourses` INT NOT NULL,
  `Teachers_idTeachers` INT NOT NULL,
  `Teachers_Contact info_idContact info` INT NOT NULL,
  PRIMARY KEY (`Courses_idCourses`, `Teachers_idTeachers`, `Teachers_Contact info_idContact info`),
  INDEX `fk_Courses_has_Teachers_Teachers1_idx` (`Teachers_idTeachers` ASC, `Teachers_Contact info_idContact info` ASC) VISIBLE,
  INDEX `fk_Courses_has_Teachers_Courses1_idx` (`Courses_idCourses` ASC) VISIBLE,
  CONSTRAINT `fk_Courses_has_Teachers_Courses1`
    FOREIGN KEY (`Courses_idCourses`)
    REFERENCES `mydb`.`Courses` (`idCourses`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Courses_has_Teachers_Teachers1`
    FOREIGN KEY (`Teachers_idTeachers` , `Teachers_Contact info_idContact info`)
    REFERENCES `mydb`.`Teachers` (`idTeachers` , `Contact info_idContact info`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Exam_Type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Exam_Type` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Exam_Type` (
  `idExam_Type` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `desc` VARCHAR(45) NULL,
  PRIMARY KEY (`idExam_Type`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Exam`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Exam` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Exam` (
  `idExam` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `start_date` DATE NULL,
  `Exam_Type_idExam_Type` INT NOT NULL,
  PRIMARY KEY (`idExam`),
  INDEX `fk_Exam_Exam_Type1_idx` (`Exam_Type_idExam_Type` ASC) VISIBLE,
  CONSTRAINT `fk_Exam_Exam_Type1`
    FOREIGN KEY (`Exam_Type_idExam_Type`)
    REFERENCES `mydb`.`Exam_Type` (`idExam_Type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Exam Result`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Exam Result` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Exam Result` (
  `idExam Result` INT NOT NULL AUTO_INCREMENT,
  `Marks` VARCHAR(45) NULL,
  `Exam_idExam` INT NOT NULL,
  `Courses_idCourses` INT NOT NULL,
  `Students_idStudent` INT NOT NULL,
  `Students_Contact info_idContact info` INT NOT NULL,
  `Students_Attendance_idAttendance` INT NOT NULL,
  PRIMARY KEY (`idExam Result`),
  INDEX `fk_Exam Result_Exam1_idx` (`Exam_idExam` ASC) VISIBLE,
  INDEX `fk_Exam Result_Courses1_idx` (`Courses_idCourses` ASC) VISIBLE,
  INDEX `fk_Exam Result_Students1_idx` (`Students_idStudent` ASC, `Students_Contact info_idContact info` ASC, `Students_Attendance_idAttendance` ASC) VISIBLE,
  CONSTRAINT `fk_Exam Result_Exam1`
    FOREIGN KEY (`Exam_idExam`)
    REFERENCES `mydb`.`Exam` (`idExam`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Exam Result_Courses1`
    FOREIGN KEY (`Courses_idCourses`)
    REFERENCES `mydb`.`Courses` (`idCourses`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Exam Result_Students1`
    FOREIGN KEY (`Students_idStudent` , `Students_Contact info_idContact info` , `Students_Attendance_idAttendance`)
    REFERENCES `mydb`.`Students` (`idStudent` , `Contact info_idContact info` , `Attendance_idAttendance`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
