-- MySQL Script generated by MySQL Workbench
-- Sat Oct  5 23:31:51 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `students` DEFAULT CHARACTER SET utf8 ;
USE `students` ;

-- -----------------------------------------------------
-- Table `mydb`.`Cars`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `students`.`Cars` ;

CREATE TABLE IF NOT EXISTS `students`.`Cars` (
  `idCars` INT NOT NULL AUTO_INCREMENT,
  `Brand` VARCHAR(45) NOT NULL,
  `Model` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCars`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Contact info`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `students`.`Contact info` ;

CREATE TABLE IF NOT EXISTS `students`.`Contact info` (
  `idContact info` INT NOT NULL AUTO_INCREMENT,
  `City` VARCHAR(45) NOT NULL,
  `Street` VARCHAR(45) NOT NULL,
  `Phone` INT NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idContact info`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Dormitories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `students`.`Dormitories` ;

CREATE TABLE IF NOT EXISTS `students`.`Dormitories` (
  `idDormitories` INT NOT NULL AUTO_INCREMENT,
  `Contact_info_fk` INT NULL,
  PRIMARY KEY (`idDormitories`),
  INDEX `fk_Dormitories_Contact info1_idx` (`Contact_info_fk` ASC) VISIBLE,
  CONSTRAINT `fk_Dormitories_Contact info1`
    FOREIGN KEY (`Contact_info_fk`)
    REFERENCES `students`.`Contact info` (`idContact info`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


CREATE TABLE IF NOT EXISTS `students`.`Dormitories` (
  `idDormitories` INT NOT NULL AUTO_INCREMENT,
  `Contact info_idContact info` INT NOT NULL,
  PRIMARY KEY (`idDormitories`, `Contact info_idContact info`),
  INDEX `fk_Dormitories_Contact info1_idx` (`Contact info_idContact info` ASC) VISIBLE,
  CONSTRAINT `fk_Dormitories_Contact info1`
    FOREIGN KEY (`Contact info_idContact info`)
    REFERENCES `students`.`Contact info` (`idContact info`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Attendance`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `students`.`Attendance` ;

CREATE TABLE IF NOT EXISTS `students`.`Attendance` (
  `idAttendance` INT NOT NULL AUTO_INCREMENT,
  `date` DATE NOT NULL,
  `status` TINYINT NULL,
  `remark` VARCHAR(45) NULL,
  PRIMARY KEY (`idAttendance`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Students`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `students`.`Students` ;

CREATE TABLE IF NOT EXISTS `students`.`Students` (
  `idStudent` INT NOT NULL AUTO_INCREMENT,
  `FirstName` VARCHAR(45) NOT NULL,
  `LastName` VARCHAR(45) NOT NULL,
  `Cars_idCars` INT NOT NULL,
  `Contact info_idContact info` INT NOT NULL,
  `Dormitories_idDormitories` INT NOT NULL,
  `Dormitories_Contact info_idContact info` INT NOT NULL,
  `Attendance_idAttendance` INT NOT NULL,
  PRIMARY KEY (`idStudent`, `Contact info_idContact info`, `Attendance_idAttendance`),
  INDEX `fk_Students_Cars_idx` (`Cars_idCars` ASC) VISIBLE,
  INDEX `fk_Students_Contact info1_idx` (`Contact info_idContact info` ASC) VISIBLE,
  INDEX `fk_Students_Dormitories1_idx` (`Dormitories_idDormitories` ASC, `Dormitories_Contact info_idContact info` ASC) VISIBLE,
  INDEX `fk_Students_Attendance1_idx` (`Attendance_idAttendance` ASC) VISIBLE,
  CONSTRAINT `fk_Students_Cars`
    FOREIGN KEY (`Cars_idCars`)
    REFERENCES `students`.`Cars` (`idCars`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Students_Contact info1`
    FOREIGN KEY (`Contact info_idContact info`)
    REFERENCES `students`.`Contact info` (`idContact info`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Students_Dormitories1`
    FOREIGN KEY (`Dormitories_idDormitories` , `Dormitories_Contact info_idContact info`)
    REFERENCES `students`.`Dormitories` (`idDormitories` , `Contact info_idContact info`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Students_Attendance1`
    FOREIGN KEY (`Attendance_idAttendance`)
    REFERENCES `students`.`Attendance` (`idAttendance`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Courses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `students`.`Courses` ;

CREATE TABLE IF NOT EXISTS `students`.`Courses` (
  `idCourses` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NULL,
  PRIMARY KEY (`idCourses`),
  UNIQUE INDEX `idCourses_UNIQUE` (`idCourses` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Courses_has_Students`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `students`.`Courses_has_Students` ;

CREATE TABLE IF NOT EXISTS `students`.`Courses_has_Students` (
  `Courses_idCourses` INT NOT NULL,
  `Students_idStudent` INT NOT NULL,
  PRIMARY KEY (`Courses_idCourses`, `Students_idStudent`),
  INDEX `fk_Courses_has_Students_Students1_idx` (`Students_idStudent` ASC) VISIBLE,
  INDEX `fk_Courses_has_Students_Courses1_idx` (`Courses_idCourses` ASC) VISIBLE,
  CONSTRAINT `fk_Courses_has_Students_Courses1`
    FOREIGN KEY (`Courses_idCourses`)
    REFERENCES `students`.`Courses` (`idCourses`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Courses_has_Students_Students1`
    FOREIGN KEY (`Students_idStudent`)
    REFERENCES `students`.`Students` (`idStudent`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Teachers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `students`.`Teachers` ;

CREATE TABLE IF NOT EXISTS `students`.`Teachers` (
  `idTeachers` INT NOT NULL AUTO_INCREMENT,
  `FirstName` VARCHAR(45) NOT NULL,
  `LastName` VARCHAR(45) NOT NULL,
  `Salary` INT NOT NULL,
  `Cars_idCars` INT NULL,
  `Contact_info_fk` INT NULL,
  PRIMARY KEY (`idTeachers`),
  INDEX `fk_Teachers_Cars1_idx` (`Cars_idCars` ASC) VISIBLE,
  INDEX `fk_Teachers_Contact info1_idx` (`Contact_info_fk` ASC) VISIBLE,
  CONSTRAINT `fk_Teachers_Cars1`
    FOREIGN KEY (`Cars_idCars`)
    REFERENCES `students`.`Cars` (`idCars`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Teachers_Contact info1`
    FOREIGN KEY (`Contact_info_fk`)
    REFERENCES `students`.`Contact info` (`idContact info`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Courses_has_Teachers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `students`.`Courses_has_Teachers` ;

CREATE TABLE IF NOT EXISTS `students`.`Courses_has_Teachers` (
  `Courses_idCourses` INT NOT NULL,
  `Teachers_idTeachers` INT NOT NULL,
  `Teachers_Contact info_idContact info` INT NOT NULL,
  PRIMARY KEY (`Courses_idCourses`, `Teachers_idTeachers`, `Teachers_Contact info_idContact info`),
  INDEX `fk_Courses_has_Teachers_Teachers1_idx` (`Teachers_idTeachers` ASC, `Teachers_Contact info_idContact info` ASC) VISIBLE,
  INDEX `fk_Courses_has_Teachers_Courses1_idx` (`Courses_idCourses` ASC) VISIBLE,
  CONSTRAINT `fk_Courses_has_Teachers_Courses1`
    FOREIGN KEY (`Courses_idCourses`)
    REFERENCES `students`.`Courses` (`idCourses`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Courses_has_Teachers_Teachers1`
    FOREIGN KEY (`Teachers_idTeachers`)
    REFERENCES `students`.`Teachers` (`idTeachers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Exam_Type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `students`.`Exam_Type` ;

CREATE TABLE IF NOT EXISTS `students`.`Exam_Type` (
  `idExam_Type` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `desc` VARCHAR(45) NULL,
  PRIMARY KEY (`idExam_Type`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Exam`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `students`.`Exam` ;

CREATE TABLE IF NOT EXISTS `students`.`Exam` (
  `idExam` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `start_date` DATE NULL,
  `Exam_Type_idExam_Type` INT NOT NULL,
  PRIMARY KEY (`idExam`),
  INDEX `fk_Exam_Exam_Type1_idx` (`Exam_Type_idExam_Type` ASC) VISIBLE,
  CONSTRAINT `fk_Exam_Exam_Type1`
    FOREIGN KEY (`Exam_Type_idExam_Type`)
    REFERENCES `students`.`Exam_Type` (`idExam_Type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Exam Result`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `students`.`Exam Result` ;

CREATE TABLE IF NOT EXISTS `students`.`Exam Result` (
  `idExam Result` INT NOT NULL AUTO_INCREMENT,
  `Marks` VARCHAR(45) NULL,
  `Exam_idExam` INT NOT NULL,
  `Courses_idCourses` INT NOT NULL,
  `Students_idStudent` INT NOT NULL,
  `Students_Contact info_idContact info` INT NOT NULL,
  `Students_Attendance_idAttendance` INT NOT NULL,
  PRIMARY KEY (`idExam Result`),
  INDEX `fk_Exam Result_Exam1_idx` (`Exam_idExam` ASC) VISIBLE,
  INDEX `fk_Exam Result_Courses1_idx` (`Courses_idCourses` ASC) VISIBLE,
  INDEX `fk_Exam Result_Students1_idx` (`Students_idStudent` ASC, `Students_Contact info_idContact info` ASC, `Students_Attendance_idAttendance` ASC) VISIBLE,
  CONSTRAINT `fk_Exam Result_Exam1`
    FOREIGN KEY (`Exam_idExam`)
    REFERENCES `students`.`Exam` (`idExam`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Exam Result_Courses1`
    FOREIGN KEY (`Courses_idCourses`)
    REFERENCES `students`.`Courses` (`idCourses`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Exam Result_Students1`
    FOREIGN KEY (`Students_idStudent` , `Students_Contact info_idContact info` , `Students_Attendance_idAttendance`)
    REFERENCES `students`.`Students` (`idStudent` , `Contact info_idContact info` , `Attendance_idAttendance`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


-- SolvdLaba13 Assigment--

INSERT INTO `students`.`Cars`
    ( Brand, Model)
VALUES
    ('BMW', 'M3'),
    ('Audi', 'A3'),
    ('Volskwagen', 'Passat'),
    ('Volskwagen', 'Golf')
    
    UPDATE `students`.`Cars`
	SET Brand = 'Aston', Model = 'Martin'
	WHERE idCars = 1;
    
	UPDATE `students`.`Cars`
	SET Brand = 'Mini', Model = 'Couper'
	WHERE idCars = 2;
    
    UPDATE `students`.`Cars`
	SET Brand = 'Aston Martin', Model = 'DB'
	WHERE idCars = 3;
    
    UPDATE `students`.`Cars`
    SET Brand = 'Piki Pompa'
    where idCars >3;
    
    UPDATE `students`.`Cars`
	SET Brand ='Lexus'
	WHERE Brand = 'Piki Pompa';
    
	DELETE FROM `students`.`Cars` WHERE Brand ='Piki Pompa';
    DELETE FROM `students`.`Cars` WHERE Model ='Passat';
    DELETE FROM `students`.`Cars` WHERE Model ='Golf';
    DELETE FROM `students`.`Cars` WHERE Model ='M3';
    DELETE FROM `students`.`Cars` WHERE Model ='A3';
    DELETE FROM `students`.`Cars`;

    
    
      INSERT INTO `students`.`Contact info` (City, Street, Phone,Email)
    VALUES 
      ('Krakow', 'Ziemniaczana 32', 541151111,'test@gmail.com'),
      ('Warsaw', 'Zamkowa 2', 123546678,'test2@gmail.com'),
      ('Lodz', 'Pilsudskiego 86', 777888999, 'test3@gmail.com'),
      ('Lodz', 'Pilsudskiego 86', 777888999, 'test3@gmail.com'),
      ('Lodz', 'Pilsudskiego 86', 777888999, 'test3@gmail.com'),
      ('Lodz', 'Pilsudskiego 86', 777888999, 'test3@gmail.com')
    
        UPDATE `students`.`Contact info`
		SET City ='London'
		WHERE City != 'Lodz';
        
          UPDATE `students`.`Contact info`
			SET City ='Berlin'
			WHERE `idContact info`  >= 2;
            
			UPDATE `students`.`Contact info`
			SET Street ='BamBamBam 23'
			WHERE idContact info  = 4;
            
            DELETE FROM `students`.`Contact info` where City = 'Lodz';
            DELETE FROM `students`.`Contact info` where email = 'test3@gmail.com';
			DELETE FROM `students`.`Contact info` where phone = '777888999';
            DELETE FROM `students`.`Contact info` where street = 'Pilsudskiego 86';
             
    
    
	INSERT INTO `students`.`Teachers`( FirstName, LastName, Salary, Cars_idCars, Contact_info_fk)
    VALUES
		('George', 'Milowsky',5000,1,1),
		('Tuti', 'Fruti',3500,2,2),
		('Anna', 'Wanna',4600,3,3)
        
        UPDATE `students`.`Teachers`
			SET FirstName = 'Janek'
			WHERE idTeachers  <3;
        
       INSERT INTO `students`.`Dormitories` ( `Contact info_idContact info`)
    VALUES (1);
    
    
    ALTER TABLE `students`.`Teachers`
    ADD  power_level INT;
    
    ALTER TABLE `students`.`Teachers`
   MODIFY power_level VARCHAR(30);
   
   ALTER TABLE `students`.`Teachers`
  CHANGE  power_level  nickname VARCHAR(30);
   
   ALTER TABLE `students`.`Teachers`
   DROP  nickname;
   
    ALTER TABLE `students`.`Contact info`
    ADD  postCode VARCHAR(45);
    
    
    SELECT * FROM students.`contact info`;
	select * from students.`Cars`;
    select * from students.`Teachers`;
    select * from students.`Dormitories`;
    
    select FirstName, LastName, Salary, City, Phone, Brand, Model from Cars join Teachers on Cars.idCars = Teachers.Cars_idCars join `Contact info` on `students`.`Contact info`.`idContact info` = Teachers.Contact_info_fk
    
    
    select * from Cars left join Teachers on Cars.idCars = Teachers.Cars_idCars;
    select * from Cars right join Teachers on Cars.idCars = Teachers.Cars_idCars;
    select * from Cars LEFT OUTER JOIN Teachers on Cars.idCars = Teachers.Cars_idCars;
    select * from Cars Right OUTER JOIN Teachers on Cars.idCars = Teachers.Cars_idCars;
    
    select * from Cars LEFT OUTER JOIN Teachers on Cars.idCars = Teachers.Cars_idCars
    UNION
    select * from Cars Right OUTER JOIN Teachers on Cars.idCars = Teachers.Cars_idCars;
    
    
    
    select COUNT(idTeachers), FirstName, LastName from Cars join Teachers on Cars.idCars = Teachers.Cars_idCars where Salary > 3700 GROUP BY (idTeachers) ORDER BY (idCars) DESC;
	select AVG(Salary) , FirstName,LastName from Cars join Teachers on Cars.idCars = Teachers.Cars_idCars where Model = 'Passat' GROUP BY (idTeachers) ORDER BY (idCars) DESC;
	select MAX(idCars), FirstName,LastName from Cars join Teachers on Cars.idCars = Teachers.Cars_idCars where FirstName = 'Anna' GROUP BY (idTeachers) ORDER BY (idCars) DESC;
    select Sum(idTeachers), FirstName,LastName from Teachers join `Contact info` on `idContact info` = Teachers.Contact_info_fk where FirstName = 'Janek' GROUP BY (idTeachers) ORDER BY (City);
    select SUM(SALARY), FirstName,LastName from Teachers join `Contact info` on `idContact info` = Teachers.Contact_info_fk where Salary < 4000 GROUP BY (idTeachers) ORDER BY (City);
    select Min(idTeachers), FirstName,LastName from Teachers join `Contact info` on `idContact info` = Teachers.Contact_info_fk where Salary > 5000 GROUP BY (idTeachers) ORDER BY (Street);
    select Count(Salary), FirstName,LastName from Teachers join `Contact info` on `idContact info` = Teachers.Contact_info_fk where FirstName != 'Janek' GROUP BY (idTeachers) ORDER BY (Street);
    
    
    SELECT COUNT(idTeachers), FirstName, LastName FROM Teachers GROUP BY (idTeachers) HAVING COUNT(idTeachers) >= 1 ORDER BY COUNT(idTeachers) DESC;
    select AVG(Salary) , FirstName,LastName from Teachers GROUP BY (idTeachers) HAVING MIN(Salary) > 4000 ORDER BY COUNT(idTeachers) DESC;
    select * from Teachers GROUP BY (idTeachers) HAVING sum(Salary) > 4000 ORDER BY COUNT(idTeachers) DESC;
    select MiN(Salary), FirstName,LastName from Teachers  GROUP BY (idTeachers) HAVING idTeachers=1 ORDER BY COUNT(idTeachers) DESC;
    select MAX(Salary), FirstName,LastName from Teachers  GROUP BY (idTeachers) HAVING idTeachers=2 ORDER BY COUNT(idTeachers) DESC;
    select MAX(idCars), Brand, Model from Cars GROUP BY (idCars) HAVING Brand = 'Volskwagen' ORDER BY COUNT(idCars) DESC;
    select COUNT(idCars), Brand, Model from Cars GROUP BY (idCars) HAVING Model = 'Golf' ORDER BY COUNT(idCars) DESC;




    
    
    